#!/usr/bin/env node
/*
 * Copyright (C) 2026 - present quite frankly an example LMS contributors
 *
 * This file is part of quite frankly an example LMS, a modified version of Canvas.
 *
 * quite frankly an example LMS is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, version 3 of the License.
 *
 * quite frankly an example LMS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

// Swaps the app's icons for Material Symbols (Sharp), from mapping.js:
//
//   1. ui/shared/material-icons/generated.ts: an InstUI-compatible component
//      for each mapped icon. The build aliases @instructure/ui-icons to
//      ui/shared/material-icons, so every React page picks them up.
//   2. public/images/material-symbols/*.svg and
//      app/stylesheets/components/_material-icon-font.scss: the legacy
//      `<i class="icon-…">` font glyphs, redrawn as SVG masks.
//   3. app/views/shared/svg: the global navigation's SVG partials.
//
// Usage (in the web container):
//   mkdir -p tmp/material-symbols && cd tmp/material-symbols \
//     && npm pack @material-symbols/svg-400 && tar xzf material-symbols-svg-400-*.tgz && cd ../..
//   node script/material_icons/generate.js [tmp/material-symbols/package/sharp]
//   npx biome format --write ui/shared/material-icons && yarn build:css
//
// Material Symbols are © Google, Apache License 2.0.

const fs = require('fs')
const path = require('path')
const {ICONS, NAV} = require('./mapping')

const root = path.resolve(__dirname, '../..')
const svgDir = path.resolve(root, process.argv[2] || 'tmp/material-symbols/package/sharp')
const instuiDir = path.join(root, 'node_modules/@instructure/ui-icons/es')
const HEADER = `/*
 * Generated by script/material_icons/generate.js from script/material_icons/mapping.js.
 * Do not edit by hand. Icons: Material Symbols (Sharp), © Google, Apache License 2.0.
 */
`

function symbol(name, fill) {
  const file = path.join(svgDir, `${name}${fill ? '-fill' : ''}.svg`)
  if (!fs.existsSync(file)) return null
  const svg = fs.readFileSync(file, 'utf8')
  const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map(match => match[1])
  return {svg, d: paths.join(' ')}
}

const missing = []
const need = (name, fill) => {
  const found = symbol(name, fill)
  if (!found) missing.push(`${name}${fill ? '-fill' : ''}`)
  return found
}

// --- 1. React components -----------------------------------------------------

const paths = {}
const components = []
for (const [base, name] of Object.entries(ICONS)) {
  for (const variant of ['Line', 'Solid']) {
    const original = path.join(instuiDir, `Icon${base}${variant}.js`)
    if (!fs.existsSync(original)) {
      missing.push(`InstUI Icon${base}${variant}`)
      continue
    }
    const fill = variant === 'Solid'
    const found = need(name, fill)
    if (!found) continue
    const key = `${name}${fill ? '-fill' : ''}`
    paths[key] = found.d
    const source = fs.readFileSync(original, 'utf8')
    const glyph = (source.match(/glyphName = '([^']+)'/) || [])[1] || base
    const bidirectional = /bidirectional: true/.test(source)
    components.push(
      `export const Icon${base}${variant} = materialIcon('Icon${base}${variant}', '${glyph}', '${variant}', P['${key}']${bidirectional ? ', true' : ''})`,
    )
  }
}

// --- 2. Legacy icon font -----------------------------------------------------

const fontDir = path.join(root, 'public/fonts/instructure_icons')
const fontNames = variant =>
  new Set(
    [
      ...fs
        .readFileSync(path.join(fontDir, variant, `InstructureIcons-${variant}_icon-map.scss`), 'utf8')
        .matchAll(/^\s+([A-Za-z0-9-]+): "/gm),
    ].map(match => match[1]),
  )
const lineNames = fontNames('Line')
const solidNames = fontNames('Solid')

// "AddFolder" -> "add-folder"; digits may or may not get their own dash
function kebabCandidates(base) {
  const words = base.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
  const plain = words.toLowerCase()
  return [plain, plain.replace(/([a-z])(\d)/g, '$1-$2'), base]
}

const fontIcons = []
for (const [base, name] of Object.entries(ICONS)) {
  const kebab = kebabCandidates(base).find(candidate => lineNames.has(candidate))
  if (!kebab) continue
  fontIcons.push({kebab, name, solid: solidNames.has(kebab)})
}

const publicDir = path.join(root, 'public/images/material-symbols')
fs.mkdirSync(publicDir, {recursive: true})
const written = new Set()
const writeSvg = (name, fill) => {
  const key = `${name}${fill ? '-fill' : ''}`
  if (written.has(key)) return
  const found = need(name, fill)
  if (!found) return
  fs.writeFileSync(
    path.join(publicDir, `${key}.svg`),
    found.svg.replace(/ width="\d+" height="\d+"/, ''),
  )
  written.add(key)
}
fontIcons.forEach(({name, solid}) => {
  writeSvg(name, false)
  if (solid) writeSvg(name, true)
})
fs.writeFileSync(
  path.join(publicDir, 'README.md'),
  'Material Symbols (Sharp), © Google, Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0).\n' +
    'Generated by script/material_icons/generate.js; used by app/stylesheets/components/_material-icon-font.scss.\n',
)

const selectors = fontIcons.map(({kebab}) => `.icon-${kebab}:before`)
const scss = [
  `// Generated by script/material_icons/generate.js from script/material_icons/mapping.js.`,
  `// Do not edit by hand. Icons: Material Symbols (Sharp), © Google, Apache License 2.0.`,
  `//`,
  `// Redraws the legacy icon font's glyphs as Material Symbols: each glyph becomes`,
  `// an SVG mask filled with the text color, so icons keep their color and size.`,
  ``,
  `${selectors.join(',\n')} {`,
  `  content: "";`,
  `  display: inline-block;`,
  `  width: 1em;`,
  `  height: 1em;`,
  `  background-color: currentColor;`,
  `  -webkit-mask: no-repeat center / contain;`,
  `  mask: no-repeat center / contain;`,
  `}`,
  ``,
  ...fontIcons.flatMap(({kebab, name, solid}) => {
    const rule = (selector, file) =>
      `${selector} { -webkit-mask-image: url("/images/material-symbols/${file}.svg"); mask-image: url("/images/material-symbols/${file}.svg"); }`
    return [
      rule(`.icon-${kebab}:before`, name),
      ...(solid ? [rule(`.icon-${kebab}.icon-Solid:before`, `${name}-fill`)] : []),
    ]
  }),
  ``,
].join('\n')
fs.writeFileSync(path.join(root, 'app/stylesheets/components/_material-icon-font.scss'), scss)

// --- 3. Global navigation SVGs ---------------------------------------------

const navDir = path.join(root, 'app/views/shared/svg')
const navDone = []
for (const [file, name] of Object.entries(NAV)) {
  const target = path.join(navDir, file)
  if (!fs.existsSync(target)) continue
  const found = need(name, false)
  if (!found) continue
  const current = fs.readFileSync(target, 'utf8')
  const open = current.match(/<svg\b[^>]*>/)[0]
  const keep = ['class', 'width', 'height', 'aria-hidden', 'role', 'focusable']
    .map(attr => (open.match(new RegExp(`\\s${attr}="[^"]*"`)) || [''])[0])
    .join('')
  const title = (current.match(/<title>[^<]*<\/title>/) || [''])[0]
  fs.writeFileSync(
    target,
    `<svg xmlns="http://www.w3.org/2000/svg"${keep} viewBox="0 -960 960 960">${title}<path d="${found.d}"/></svg>\n`,
  )
  navDone.push(file)
}

// --- write the components and report -----------------------------------------

const outDir = path.join(root, 'ui/shared/material-icons')
fs.mkdirSync(outDir, {recursive: true})
fs.writeFileSync(
  path.join(outDir, 'generated.ts'),
  `${HEADER}
import {materialIcon} from './materialIcon'

const P: Record<string, string> = ${JSON.stringify(paths, null, 2)}

${components.join('\n')}
`,
)

// Named re-exports win over `export *`; two star exports of the same name
// would cancel each other out, so the Material icons are listed by name.
const names = components.map(line => line.match(/^export const (\w+)/)[1])
fs.writeFileSync(
  path.join(outDir, 'index.ts'),
  `${HEADER}
// Stands in for @instructure/ui-icons in the build (ui-build/webpack aliases
// the package here): every InstUI icon, with the ones in
// script/material_icons/mapping.js redrawn as Material Symbols (Sharp).
// Unmapped icons (brand logos and the like) pass through unchanged.
export * from '@instructure/ui-icons/es/index.js'
export {
${names.map(name => `  ${name},`).join('\n')}
} from './generated'
`,
)

console.log(
  `components: ${components.length}, font glyphs: ${fontIcons.length}, svg files: ${written.size}, nav svgs: ${navDone.length}`,
)
if (missing.length) {
  console.error(`missing: ${[...new Set(missing)].join(', ')}`)
  process.exitCode = 1
}
