production: &production
  address: mailcatcher
  port: 1025
  domain: canvas.docker
  outgoing_address: canvas@canvas.docker
  default_name: quite frankly an example LMS

development:
  <<: *production
