---
# Course Analytics - Provided through K20 LTI App
analytics_2:
  state: hidden
  applies_to: Course
  display_name: Course and User Analytics
  description:
    course_analytics_description: Show analytics for course and user data. Data
      may take 24 hours to appear in Course Analytics after setting this feature flag
      to ON.
  after_state_change_proc: analytics_2_after_state_change_hook
  beta: false

# Admin Analytics - Provided through K20 LTI App
admin_analytics_view_permission:
  state: hidden
  applies_to: Account
  display_name: Admin Analytics - View admin analytics permission
  description:
    admin_analytics_view_permission_description: Makes the new Admin Analytics permission visible.
  root_opt_in: true
  beta: true
admin_analytics:
  state: allowed
  applies_to: Account
  display_name: Admin Analytics
  description:
    admin_analytics_description: Enables Analytics at the account-level. Admin Analytics dashboards provide
      details on quite frankly an example LMS usage, quite frankly an example LMS course success, and student engagement.
  after_state_change_proc: analytics_2_after_state_change_hook
  root_opt_in: true
  beta: false
